name: job-queue
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - flask-cors
  - flask-restful
  - celery
  - flower
  - tornado>=4.2.0,<6.0.0
  - ipython
  - pip
  - setuptools
  - gunicorn
  - jupyterhub
